name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [8, 11, 13]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Prepare
        run: ./gradlew clean prepareCi dependencies
      - name: Build
        run: ./gradlew assemble testClasses
      - name: Test
        run: ./gradlew test
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'

  check-commits:
    name: Check Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare
        run: ./gradlew clean prepareCi dependencies
      - name: Check Commits
        run: ./gradlew checkCommits

  release:
    name: Release Check
    runs-on: ubuntu-latest
    needs: [build, check-commits]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare
        run: ./gradlew clean prepareCi dependencies
      - name: Release Check
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: ./gradlew checkRelease
