name: Dependency Graph

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  submit:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set Up Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version-file: '.sdkmanrc'
          distribution: temurin

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
