name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release Artefacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            .yarn/cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*', 'yarn.lock') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare
        run: ./gradlew clean prepareCi dependencies
      - name: Assemble Artefacts
        run: ./gradlew assemble
        env:
           ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}
      - name: Release Artefacts
        run: ./gradlew release
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PACKAGE_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.PACKAGE_SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}

  docs:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            .yarn/cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.*', 'yarn.lock') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare
        run: ./gradlew clean prepareCi dependencies
      - name: Generate Documentation
        run: ./gradlew dokka
        env:
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}
      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3.0.3
        with:
          publish_dir: ./build/dokka
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
