name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release Artefacts
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Read Java Version from .sdkmanrc
        id: sdkmanrc
        run: |
          version=$(sed -n 's/^java=\([^-]*\).*/\1/p' .sdkmanrc)
          echo "java-version=$version" >> "$GITHUB_OUTPUT"

      - name: Set Up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ steps.sdkmanrc.outputs.java-version }}
          distribution: temurin

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5

      - name: Assemble Artefacts
        run: ./gradlew assemble
        env:
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}

      - name: Release Artefacts
        run: ./gradlew release
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PACKAGE_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.PACKAGE_SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
