name: Release

on:
  release:
    types: [ published ]

env:
  ORG_GRADLE_PROJECT_version: ${{ github.event.release.tag_name }}

jobs:
  release:
    name: Release Artefacts
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set Up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version-file: '.sdkmanrc'
          distribution: temurin

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Assemble Artefacts
        run: ./gradlew assemble
        env:
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}

      - name: Release Artefacts
        run: ./gradlew release
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PACKAGE_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.PACKAGE_SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}

      - name: Generate Documentation
        run: ./gradlew dokkaGeneratePublicationHtml
        env:
          ORG_GRADLE_PROJECT_githubRepository: ${{ github.repository }}

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./build/dokka/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
