# See https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
# for more info on this workflow

name: Test Report

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  add_report:
    name: Annotate Test Results on Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2
        with:
          artifact: /test-results-.*/
          name: Test Results
          path: "**/*.xml"
          reporter: java-junit
          max-annotations: "50"
          fail-on-error: "false"
